/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseAccordion: typeof import('./src/components/base/accordion/BaseAccordion.vue')['default']
    BaseBadge: typeof import('./src/components/base/badge/BaseBadge.vue')['default']
    BaseButton: typeof import('./src/components/base/button/BaseButton.vue')['default']
    BaseCard: typeof import('./src/components/base/card/BaseCard.vue')['default']
    BaseCarousel: typeof import('./src/components/base/carousel/BaseCarousel.vue')['default']
    BaseChip: typeof import('./src/components/base/chip/BaseChip.vue')['default']
    BaseDialog: typeof import('./src/components/base/dialog/BaseDialog.vue')['default']
    BaseElementsContainer: typeof import('./src/components/base/elements-container/BaseElementsContainer.vue')['default']
    BaseProfileImageBox: typeof import('./src/components/base/profile-image-box/BaseProfileImageBox.vue')['default']
    IconCustomFacebook: typeof import('~icons/custom/facebook')['default']
    IconCustomInstagram: typeof import('~icons/custom/instagram')['default']
    IconCustomLogo: typeof import('~icons/custom/logo')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheAppContainer: typeof import('./src/components/layouts/app-container/TheAppContainer.vue')['default']
    TheFooter: typeof import('./src/components/layouts/footer/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/layouts/header/TheHeader.vue')['default']
    TheInlineNavbar: typeof import('./src/components/layouts/inline-navbar/TheInlineNavbar.vue')['default']
    ThePageContainer: typeof import('./src/components/layouts/page-container/ThePageContainer.vue')['default']
    ThePageLoader: typeof import('./src/components/layouts/page-loader/ThePageLoader.vue')['default']
    TheSideNavbar: typeof import('./src/components/layouts/side-navbar/TheSideNavbar.vue')['default']
  }
}
